apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: knwv3yzwa-python
  janus-idp.io/tekton: knwv3yzwa-python
  backstage.io/kubernetes-id: knwv3yzwa-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: knwv3yzwa-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
